# K Fold Cross Validation

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [2]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits['data'],digits['target'],test_size=0.3)

In [4]:
lr = LogisticRegression(solver='sag',max_iter=1000)
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

c:\Users\naman\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


0.9648148148148148

In [5]:
lr = SVC()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9907407407407407

In [6]:
lr = RandomForestClassifier()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9851851851851852

In [7]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [8]:
# KFold working DEMO
for train_index , test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [9]:
def get_scores(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [10]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [11]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index , test_index in kf.split(digits['data']):
    X_train,X_test,y_train,y_test = digits['data'][train_index], digits['data'][test_index], digits['target'][train_index], digits['target'][test_index]

    scores_l.append(get_scores(LogisticRegression(solver='sag',max_iter=1000),X_train,X_test,y_train,y_test))
    scores_svm.append(get_scores(SVC(),X_train,X_test,y_train,y_test))
    scores_rf.append(get_scores(RandomForestClassifier(n_estimators=40),X_train,X_test,y_train,y_test))

In [12]:
scores_l

[0.9282136894824707, 0.9415692821368948, 0.9115191986644408]

In [13]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [14]:
scores_rf

[0.9365609348914858, 0.9515859766277128, 0.9165275459098498]

### Doing all this by using sklearn's cross_val_score

In [15]:
from sklearn.model_selection import cross_val_score

In [16]:
cross_val_score(LogisticRegression(solver='sag',max_iter=1000),digits['data'],digits['target'])

c:\Users\naman\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


array([0.91944444, 0.86944444, 0.94428969, 0.93871866, 0.89693593])

In [17]:
cross_val_score(SVC(),digits['data'],digits['target'])

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [18]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits['data'],digits['target'])

array([0.925     , 0.9       , 0.96100279, 0.95264624, 0.90807799])

In [19]:
cross_val_score(RandomForestClassifier(n_estimators=5),digits['data'],digits['target'])

array([0.84444444, 0.76944444, 0.91643454, 0.89972145, 0.84122563])

In [20]:
cross_val_score(RandomForestClassifier(n_estimators=55),digits['data'],digits['target'])

array([0.93888889, 0.91666667, 0.95821727, 0.95821727, 0.92479109])